### ISSUE TITLE
Help Error

### ISSUE THREAD

**Issue by CoehManeh** [mudroock/Gesior-AAC#1]
Error occured!

Error ID: #C-2
More info: ERROR: #C-2 : Class::ConfigLUA - LUA config file doesn't exist. Path: config.lua

File: C:\xampp\htdocs\Gesior-AAC-master\classes/configlua.php   Line: 24
File: C:\xampp\htdocs\Gesior-AAC-master\classes/configlua.php   Line: 12
File: C:\xampp\htdocs\Gesior-AAC-master\system/load.init.php   Line: 42
File: C:\xampp\htdocs\Gesior-AAC-master/index.php   Line: 20

**Comment by mudroock** [comment]
Corrigido via WPP!
