### ISSUE TITLE
adminpanel.PHP

### ISSUE THREAD

**Issue by JavEver** [mudroock/Gesior-AAC#2]
Por que o adminpanel.php  na parte dos Newsticker, deletam todos em vez de deletar só o ultimo postado ou selecionar qual que você quer deletar?

**Comment by mudroock** [comment]
Buscando informações sobre o bug.

**Comment by JavEver** [comment]
Adiciona um newstickers no site, alias mais de 1, e depois tenta deletar o último que você postou, vai ver que deleta todos.

**Comment by JavEver** [comment]
Parece que adiciona o newstickers com id = 0, e quando vai deletar com o ID deleta todos já que todos são ids iguais.

**Comment by mudroock** [comment]
Já encontrou alguma possível solução ?

**Comment by Crock-Linux** [comment]
vou postar correção....

**Comment by JavEver** [comment]
@Crock-Linux  fico no aguardo!
