### ISSUE TITLE
Fatal error!

### ISSUE THREAD

**Issue by dmludke** [mudroock/Gesior-AAC#2]
Fatal error: Uncaught Error: Call to a member function fetchAll() on boolean in C:\xampp\htdocs\pages\latestnews.php:174 Stack trace: #0 C:\xampp\htdocs\system\load.page.php(7): include() #1 C:\xampp\htdocs\index.php(37): include_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\pages\latestnews.php on line 174

**Comment by mudroock** [comment]
Use a database that I made available with the site.
