### ISSUE TITLE
Não reconhece "Free account" no personagem.

### ISSUE THREAD

**Issue by johnbrasil** [mudroock/Gesior-AAC#22]
Quando você seleciona um personagem e vê o "Account status" Abaixo:

![image](https://user-images.githubusercontent.com/32914804/31745344-1c465f78-b441-11e7-983e-82d853b1d60b.png)

Aparece sempre desta forma, Premium account, mesmo o Player estando "Free account"

Testei de todas as formas, criei varias contas, e mesmo assim, ele não reconhece que o player é Free, somente Premmy sempre.

**Comment by mudroock** [comment]
@johnbrasil Verifica se no server não está freepremium

**Comment by Mesosot** [comment]
i got the same too

**Comment by johnbrasil** [comment]
@mudroock 
Está **FALSE** mano....
