### ISSUE TITLE
account management Create Character styel

### ISSUE THREAD

**Issue by Mesosot** [mudroock/Gesior-AAC#26]
They style it really looking after i add the Vocations and towns the style it looks like that :- 
![untitlsdfsdfsdfed](https://user-images.githubusercontent.com/32135023/31768464-5ae54698-b484-11e7-9731-aa1856ee5992.png)
so i edited it on paint so it should looks like that for better view :- 
![untisdftled](https://user-images.githubusercontent.com/32135023/31768490-74c96468-b484-11e7-8576-e488905904ca.png)
thanks

**Comment by mudroock** [comment]
This is not a bug, it's just the look you want!
Use issues only to report problems.

**Comment by Mesosot** [comment]
Okay 👌 i just wanted it to looks good anyway ,,
I will try to code it and send u the code to add it for everyone
