### ISSUE TITLE
Can't create characters

### ISSUE THREAD

**Issue by EstebPain** [mudroock/Gesior-AAC#4]
Hello!
I'm trying to make an character in the site using schema.sql as database, I'm getting this error when I make a player once loged in:
[https://image.prntscr.com/image/VlStEMP4R0q75Y7Z_ExSNw.png](https://image.prntscr.com/image/VlStEMP4R0q75Y7Z_ExSNw.png)
config.php and config.lua are ok, I have triple-checked it, I just can't make a player.
I'm using erick global ot compilated 2 days ago.

**Comment by mudroock** [comment]
I believe you are not using a database that I have downloaded with the server.

**Comment by EstebPain** [comment]
How can I check? can you handle the db? what server are you using? I choose this one because it was the one erick suggested in his git [https://github.com/malucooo/otxserver-new/](https://github.com/malucooo/otxserver-new/)
that is the server i'm using now

**Comment by mudroock** [comment]
I just updated the database to OTX and will soon release another patch to remove unused tables that can cause lag on the server in the long run.

Use the latest version and report problems for me!
