### ISSUE TITLE
dntpagseguro.php

### ISSUE THREAD

**Issue by robertof157** [mudroock/Gesior-AAC#5]
is giving weekly error every time

**Comment by mudroock** [comment]
I need more information about the problem.

**Comment by robertof157** [comment]
Esta página não está funcionando

[http://imageshack.com/a/img924/306/myYzeA.jpg](url)

This page is not working

**Comment by mudroock** [comment]
Está utilizando a database correta ?

**Comment by robertof157** [comment]
vou verificar

**Comment by robertof157** [comment]
testei com sua database e nada

**Comment by hudsonof** [comment]
Estou com o mesmo problema, to tentando encontrar o erro, mas sem sucesso ainda...

**Comment by MichelFigueira** [comment]
Eu também estou com o mesmo problema. Creio que foi alguma alteracao do pagseguro... Testei com outros projetos do Gesior e ocorre a mesma coisa :(

**Comment by mudroock** [comment]
Muita gente está com esse problema, vou buscar uma solução assim que possivel.

**Comment by Fmjj** [comment]
Boa tarde caso usem o ubuntu execute o comando:
`apt-get install php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl`


no meu caso resolveu.

**Comment by hudsonof** [comment]
Aparentemente era alguma extensão que estava faltando, ou em conflito, tive que desinstalar totalmente o php e instalar novamente só com as extensões necessárias, ai funcionou.
