### ISSUE TITLE
LatestNews.PHP

### ISSUE THREAD

**Issue by JavEver** [mudroock/Gesior-AAC#6]
Dúvida ou BUG?
Quando posto um ticket pelo adminpanel, se ele tiver mais de 5 linhas a 6° não aparece, isso da para ser alterado? se sim como?

**Comment by mudroock** [comment]
Buscando por informações.

**Comment by Crock-Linux** [comment]
para aumentar quantidade de texto execute isso 👍 
ALTER TABLE `newsticker` CHANGE COLUMN `text` `text` VARCHAR(300);

onde 300 quantidade de caracteres que deseja...aumente seu gosto.

também baixe LatestNews.PHP novamente apos pull ou altere linha

<div id="TickerEntry-'.$number_of_tickers.'-ShortText" class="NewsTickerShortText">'.short_text($ticker['text'], 60).'</div>

onde 60 quantidade de carácter que vai aparecer home
