### ISSUE TITLE
I can not create accounts and characters

### ISSUE THREAD

**Issue by carlosjfernandes** [mudroock/Gesior-AAC#8]
Hi congratulations for your great work, since yesterday I encounter this headache.

The first problem is that the registry does not work, when registering everything seems to have created an account but the database is intact, it is not registered although the page shows that it did.

The second problem is that trying to create a character with an existing account shows the following error:

Error ID: Can not save ItemsList. Player ID not set.
More info:

File: /var/www/html/classes/itemslist.php Line: 67
File: /var/www/html/classes/player.php Line: 88
File: /var/www/html/pages/accountmanagement.php Line: 4526
File: /var/www/html/system/load.page.php Line: 7
File: /var/www/html/index.php Line: 39

I'm not sure what the problem is but it looks more like a server. I am using the **database that is in the repository** with the malucooo files and using Ubuntu Server in a VPS with PHP7.0 and MySQL server 5.

**Comment by MichelFigueira** [comment]
Opa Carlos, ativa o modo debug no index.php
Ele vai dar erro em algumas colunas na hora do insert...

Se nao me engano o problema esta:

accounts.create_ip = O valor que o php esta inserindo é maior que o campo INT. Alterei para VARCHAR mesmo e resolveu.
accounts.birth_date = Coloquei como padrao NULL se caso nao recebe informacao pelo PHP.
accounts.gender = Coloquei como padrao NULL se caso nao recebe informacao pelo PHP.

players.create_ip = Mesma questao da tabela accounts. Resolvi alterando para VARCHAR.

Vlws

**Comment by mudroock** [comment]
Carlos, utilize a tabela que vem junto com o site pois é basicamente a mesma do Érick com diferença que existe algumas tabelas que são necessárias para funcionamento do site.
O site está sendo usado no servidor Malvera Global como site oficial e a mesma database que está junto com ele, tudo está funcionando perfeitamente.

**Comment by carlosjfernandes** [comment]
Hola disculpen que no hable portugués, pero @mudroock acabo de usar el squema.sql y no se registra la cuenta ademas tampoco muestra algún tipo de error. Usted puede verificarlo aquí en: **anubis.servegame.com**

**Comment by MichelFigueira** [comment]
Lo siento, pensé que era brasileño jaja
Puede activar el modo debug en index.php para que pueda ayudar?

Sólo cambia la línea 6 en index.php:
De: define('DEBUG_DATABASE',false);
Para: define('DEBUG_DATABASE',true);

**Comment by mudroock** [comment]
![image](https://user-images.githubusercontent.com/26801045/30509151-b7ae0708-9a7f-11e7-8d6f-494ed6f6927d.png)

**Comment by MichelFigueira** [comment]
@mudroock Ele informa que criou mas nao criou. Testei isso tambem ashuhaushua
Tenta logar que vai dizer que esta incorreto as infos...

Quase certeza que é o create_ip das tabelas account e character...
A base de dados esta como INT, mas o valor que o php está jogando ultrapassa o limite do INT

**Comment by mudroock** [comment]
@MichelFigueira provavelmente ele não está utilizando a schema que deixei! 
Testei em casa e não tive problemas nenhum.
